// Predefined movies for each genre category
// Each category has 10 movies to ensure stability

export const MOVIES_BY_GENRE = {
  'Sci-Fi': [
    { id: '1', title: 'Blade Runner', year: '1982', director: 'Ridley Scott', plot: 'A blade runner must pursue and terminate four replicants who stole a ship in space and have returned to Earth to find their creator.', tagline: 'Man has made his match... now it\'s his problem.', rating: '4.5/5', posterPath: null },
    { id: '2', title: 'The Matrix', year: '1999', director: 'The Wachowskis', plot: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.', tagline: 'Welcome to the Real World.', rating: '4.8/5', posterPath: null },
    { id: '3', title: '2001: A Space Odyssey', year: '1968', director: 'Stanley Kubrick', plot: 'Humanity finds a mysterious object buried beneath the lunar surface and sets off on a quest with the intelligent supercomputer H.A.L. 9000.', tagline: 'The Ultimate Trip.', rating: '4.7/5', posterPath: null },
    { id: '4', title: 'Alien', year: '1979', director: 'Ridley Scott', plot: 'The crew of a commercial spacecraft encounter a deadly lifeform after investigating an unknown transmission.', tagline: 'In space no one can hear you scream.', rating: '4.6/5', posterPath: null },
    { id: '5', title: 'Star Wars', year: '1977', director: 'George Lucas', plot: 'Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire\'s world-destroying battle station.', tagline: 'A long time ago in a galaxy far, far away...', rating: '4.9/5', posterPath: null },
    { id: '6', title: 'The Terminator', year: '1984', director: 'James Cameron', plot: 'A human soldier is sent from 2029 to 1984 to stop an almost indestructible cyborg killing machine, sent from the same year, which has been programmed to execute a young woman.', tagline: 'The thing that won\'t die, in the nightmare that won\'t end.', rating: '4.4/5', posterPath: null },
    { id: '7', title: 'Back to the Future', year: '1985', director: 'Robert Zemeckis', plot: 'Marty McFly, a 17-year-old high school student, is accidentally sent 30 years into the past in a time-traveling DeLorean invented by his close friend, the maverick scientist Doc Brown.', tagline: 'He\'s the only kid ever to get into trouble before he was born.', rating: '4.7/5', posterPath: null },
    { id: '8', title: 'The Fifth Element', year: '1997', director: 'Luc Besson', plot: 'In the colorful future, a cab driver unwittingly becomes the central figure in the search for a legendary cosmic weapon to keep Evil and Mr. Zorg at bay.', tagline: 'There is no future without it.', rating: '4.3/5', posterPath: null },
    { id: '9', title: 'Total Recall', year: '1990', director: 'Paul Verhoeven', plot: 'When a man goes for virtual vacation memories of the planet Mars, an unexpected and harrowing series of events forces him to go to the planet for real - or is he?', tagline: 'They stole his mind, now he wants it back.', rating: '4.2/5', posterPath: null },
    { id: '10', title: 'Close Encounters of the Third Kind', year: '1977', director: 'Steven Spielberg', plot: 'Roy Neary, an Indiana electric lineman, finds his quiet and ordinary daily life turned upside down after a close encounter with a UFO.', tagline: 'We are not alone.', rating: '4.5/5', posterPath: null },
  ],
  'Noir': [
    { id: '11', title: 'The Maltese Falcon', year: '1941', director: 'John Huston', plot: 'A private detective takes on a case that involves him with three eccentric criminals, a gorgeous liar, and their quest for a priceless statuette.', tagline: 'A story as explosive as his blazing automatics!', rating: '4.6/5', posterPath: null },
    { id: '12', title: 'Double Indemnity', year: '1944', director: 'Billy Wilder', plot: 'An insurance representative lets himself be talked into a murder/insurance fraud scheme that arouses an insurance investigator\'s suspicions.', tagline: 'From the moment they met it was murder!', rating: '4.7/5', posterPath: null },
    { id: '13', title: 'The Big Sleep', year: '1946', director: 'Howard Hawks', plot: 'Private detective Philip Marlowe is hired by a wealthy family. Before the complex case is over, he\'s seen murder, blackmail, and what might be love.', tagline: 'The picture they were born for!', rating: '4.5/5', posterPath: null },
    { id: '14', title: 'Sunset Boulevard', year: '1950', director: 'Billy Wilder', plot: 'A screenwriter develops a dangerous relationship with a faded film star determined to make a triumphant return.', tagline: 'A Hollywood Story.', rating: '4.8/5', posterPath: null },
    { id: '15', title: 'Touch of Evil', year: '1958', director: 'Orson Welles', plot: 'A stark, perverse story of murder, kidnapping, and police corruption in a Mexican border town.', tagline: 'The strangest vengeance ever planned!', rating: '4.6/5', posterPath: null },
    { id: '16', title: 'Chinatown', year: '1974', director: 'Roman Polanski', plot: 'A private detective investigating an adultery case stumbles on to a scheme of murder that has something to do with water.', tagline: 'Forget it, Jake. It\'s Chinatown.', rating: '4.7/5', posterPath: null },
    { id: '17', title: 'The Third Man', year: '1949', director: 'Carol Reed', plot: 'Pulp novelist Holly Martins travels to shadowy, postwar Vienna, only to find himself investigating the mysterious death of an old friend, Harry Lime.', tagline: 'The picture that will live forever!', rating: '4.8/5', posterPath: null },
    { id: '18', title: 'Laura', year: '1944', director: 'Otto Preminger', plot: 'A police detective falls in love with the woman whose murder he is investigating.', tagline: 'The story of a love that became the most fearful thing that ever happened to a woman!', rating: '4.5/5', posterPath: null },
    { id: '19', title: 'The Killers', year: '1946', director: 'Robert Siodmak', plot: 'Hit men kill an unresisting victim, prompting an insurance investigator to uncover the victim\'s past.', tagline: 'The most exciting story ever told!', rating: '4.4/5', posterPath: null },
    { id: '20', title: 'Out of the Past', year: '1947', director: 'Jacques Tourneur', plot: 'A private eye escapes his past to run a gas station in a small town, but his past catches up with him.', tagline: 'The most exciting story ever told!', rating: '4.6/5', posterPath: null },
  ],
  'Western': [
    { id: '21', title: 'The Good, the Bad and the Ugly', year: '1966', director: 'Sergio Leone', plot: 'While the Civil War rages between the Union and the Confederacy, three men hunt for the fortune in gold buried in a remote cemetery.', tagline: 'For three men the Civil War wasn\'t hell. It was practice.', rating: '4.9/5', posterPath: null },
    { id: '22', title: 'Once Upon a Time in the West', year: '1968', director: 'Sergio Leone', plot: 'A mysterious stranger with a harmonica joins forces with a notorious desperado to protect a beautiful widow from a ruthless assassin working for the railroad.', tagline: 'There were three men in her life. One to take her... one to love her... and one to kill her.', rating: '4.8/5', posterPath: null },
    { id: '23', title: 'High Noon', year: '1952', director: 'Fred Zinnemann', plot: 'A town marshal, forced to face a gang of killers by himself, is abandoned by the cowardly townspeople.', tagline: 'The story of a man who was too proud to run.', rating: '4.7/5', posterPath: null },
    { id: '24', title: 'The Searchers', year: '1956', director: 'John Ford', plot: 'An American Civil War veteran embarks on a years-long journey to rescue his niece from the Comanches after the rest of his brother\'s family is massacred in a raid on their Texas farm.', tagline: 'The biggest, roughest, toughest adventure ever!', rating: '4.8/5', posterPath: null },
    { id: '25', title: 'Unforgiven', year: '1992', director: 'Clint Eastwood', plot: 'Retired Old West gunslinger William Munny reluctantly takes on one last job, with the help of his old partner and a young man.', tagline: 'Some legends will never be forgotten. Some wrongs can never be forgiven.', rating: '4.6/5', posterPath: null },
    { id: '26', title: 'Butch Cassidy and the Sundance Kid', year: '1969', director: 'George Roy Hill', plot: 'Two Western bank/train robbers flee to Bolivia when the law gets too close.', tagline: 'Not that it matters, but most of it is true.', rating: '4.5/5', posterPath: null },
    { id: '27', title: 'True Grit', year: '1969', director: 'Henry Hathaway', plot: 'A drunken, hard-nosed U.S. Marshal and a Texas Ranger help a stubborn teenager track down her father\'s murderer in Indian territory.', tagline: 'The strangest trio ever to track a killer!', rating: '4.4/5', posterPath: null },
    { id: '28', title: 'Shane', year: '1953', director: 'George Stevens', plot: 'A weary gunfighter attempts to settle down with a homestead family, but a smoldering settler/rancher conflict forces him to act.', tagline: 'The story of a man who was too proud to run.', rating: '4.7/5', posterPath: null },
    { id: '29', title: 'The Wild Bunch', year: '1969', director: 'Sam Peckinpah', plot: 'An aging group of outlaws look for one last big score as the "traditional" American West is disappearing around them.', tagline: 'Unchanged men in a changing land. Out of step, out of place and desperately out of time.', rating: '4.6/5', posterPath: null },
    { id: '30', title: 'Stagecoach', year: '1939', director: 'John Ford', plot: 'A group of people traveling on a stagecoach find their journey complicated by the threat of Geronimo and learn something about each other in the process.', tagline: 'The greatest stagecoach adventure of all time!', rating: '4.5/5', posterPath: null },
  ],
  'Horror': [
    { id: '31', title: 'The Exorcist', year: '1973', director: 'William Friedkin', plot: 'When a 12-year-old girl is possessed by a mysterious entity, her mother seeks the help of two priests to save her.', tagline: 'Something almost beyond comprehension is happening to a girl on this street, in this house... and a man has been sent for as a last resort.', rating: '4.7/5', posterPath: null },
    { id: '32', title: 'The Shining', year: '1980', director: 'Stanley Kubrick', plot: 'A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence, while his psychic son sees horrific forebodings from both past and future.', tagline: 'The tide of terror that swept America IS HERE!', rating: '4.8/5', posterPath: null },
    { id: '33', title: 'Psycho', year: '1960', director: 'Alfred Hitchcock', plot: 'A Phoenix secretary embezzles $40,000 from her employer\'s client, goes on the run, and checks into a remote motel run by a young man under the domination of his mother.', tagline: 'A new—and altogether different—screen excitement!', rating: '4.9/5', posterPath: null },
    { id: '34', title: 'Halloween', year: '1978', director: 'John Carpenter', plot: 'Fifteen years after murdering his sister on Halloween night 1963, Michael Myers escapes from a mental hospital and returns to the small town of Haddonfield to kill again.', tagline: 'The night HE came home!', rating: '4.6/5', posterPath: null },
    { id: '35', title: 'The Texas Chain Saw Massacre', year: '1974', director: 'Tobe Hooper', plot: 'Five friends head out to rural Texas to visit the grave of a grandfather. On the way they stumble across what appears to be a deserted house, only to discover something sinister within.', tagline: 'Who will survive and what will be left of them?', rating: '4.5/5', posterPath: null },
    { id: '36', title: 'Night of the Living Dead', year: '1968', director: 'George A. Romero', plot: 'A group of people try to survive an attack of bloodthirsty zombies while trapped in a rural Pennsylvania farmhouse.', tagline: 'They won\'t stay dead!', rating: '4.7/5', posterPath: null },
    { id: '37', title: 'Rosemary\'s Baby', year: '1968', director: 'Roman Polanski', plot: 'A young couple move into an apartment, only to be surrounded by peculiar neighbors and occurrences. When the wife becomes mysteriously pregnant, paranoia over the safety of her unborn child begins to control her life.', tagline: 'Pray for Rosemary\'s Baby.', rating: '4.6/5', posterPath: null },
    { id: '38', title: 'The Omen', year: '1976', director: 'Richard Donner', plot: 'Mysterious deaths surround an American ambassador. Could the child that he is raising actually be the Antichrist? The Devil\'s own son?', tagline: 'You have been warned.', rating: '4.4/5', posterPath: null },
    { id: '39', title: 'Carrie', year: '1976', director: 'Brian De Palma', plot: 'Carrie White, a shy, friendless teenage girl who is sheltered by her domineering, religious mother, unleashes her telekinetic powers after being humiliated by her classmates at her senior prom.', tagline: 'If you\'ve got a taste for terror... take Carrie to the prom.', rating: '4.5/5', posterPath: null },
    { id: '40', title: 'The Thing', year: '1982', director: 'John Carpenter', plot: 'A research team in Antarctica is hunted by a shape-shifting alien that assumes the appearance of its victims.', tagline: 'Man is the warmest place to hide.', rating: '4.7/5', posterPath: null },
  ],
  'Rom-Com': [
    { id: '41', title: 'When Harry Met Sally...', year: '1989', director: 'Rob Reiner', plot: 'Harry and Sally meet when she gives him a ride to New York, and in a subsequent meeting ten years later, they struggle to resist their mutual attraction.', tagline: 'Can two friends sleep together and still love each other in the morning?', rating: '4.6/5', posterPath: null },
    { id: '42', title: 'Pretty Woman', year: '1990', director: 'Garry Marshall', plot: 'A man in a legal but hurtful business needs an escort for some social events, and hires a beautiful prostitute he meets... only to fall in love.', tagline: 'Who knew it was so much fun to be a hooker?', rating: '4.5/5', posterPath: null },
    { id: '43', title: 'Sleepless in Seattle', year: '1993', director: 'Nora Ephron', plot: 'A recently widowed man\'s son calls a radio talk-show in an attempt to find his father a partner.', tagline: 'What if someone you never met, someone you never saw, someone you never knew was the only someone for you?', rating: '4.4/5', posterPath: null },
    { id: '44', title: 'You\'ve Got Mail', year: '1998', director: 'Nora Ephron', plot: 'Two business rivals who despise each other in real life unwittingly fall in love over the Internet.', tagline: 'At odds in life... in love on-line.', rating: '4.3/5', posterPath: null },
    { id: '45', title: 'Notting Hill', year: '1999', director: 'Roger Michell', plot: 'The life of a simple bookshop owner changes when he meets the most famous film star in the world.', tagline: 'Can the most famous film star in the world fall for the man on the street?', rating: '4.5/5', posterPath: null },
    { id: '46', title: 'Four Weddings and a Funeral', year: '1994', director: 'Mike Newell', plot: 'Over the course of five social occasions, a committed bachelor must consider the notion that he may have discovered love.', tagline: 'Five good reasons to stay single.', rating: '4.4/5', posterPath: null },
    { id: '47', title: 'My Best Friend\'s Wedding', year: '1997', director: 'P.J. Hogan', plot: 'When a woman\'s best friend gets engaged, she realizes she\'s in love with him and sets out to get him, with only days before the wedding.', tagline: 'She\'s got four days to break up a wedding and steal the groom.', rating: '4.3/5', posterPath: null },
    { id: '48', title: '10 Things I Hate About You', year: '1999', director: 'Gil Junger', plot: 'A high-school boy, Cameron, cannot date Bianca until her anti-social older sister, Kat, has a boyfriend. So, he pays a mysterious boy, Patrick, to charm her.', tagline: 'How do I loathe thee? Let me count the ways.', rating: '4.5/5', posterPath: null },
    { id: '49', title: 'The Princess Bride', year: '1987', director: 'Rob Reiner', plot: 'While home sick in bed, a young boy\'s grandfather reads him the story of a farmboy-turned-pirate who encounters numerous obstacles, enemies and allies in his quest to be reunited with his true love.', tagline: 'As you wish.', rating: '4.8/5', posterPath: null },
    { id: '50', title: 'While You Were Sleeping', year: '1995', director: 'Jon Turteltaub', plot: 'A hopelessly romantic Chicago transit worker pulls a man from the tracks, is mistaken for his fiancée, then things get really complicated.', tagline: 'She\'s the woman of his dreams. He just doesn\'t know it yet.', rating: '4.4/5', posterPath: null },
  ],
  'Kung Fu': [
    { id: '51', title: 'Enter the Dragon', year: '1973', director: 'Robert Clouse', plot: 'A martial artist agrees to spy on a reclusive crime lord using his invitation to a tournament there.', tagline: 'The ultimate in martial arts action!', rating: '4.7/5', posterPath: null },
    { id: '52', title: 'Crouching Tiger, Hidden Dragon', year: '2000', director: 'Ang Lee', plot: 'A young Chinese warrior steals a sword from a famed swordsman and then escapes into a world of romantic adventure with a mysterious man in the frontier of the nation.', tagline: 'A timeless story of strength, secrets and two warriors who would never surrender.', rating: '4.8/5', posterPath: null },
    { id: '53', title: 'The 36th Chamber of Shaolin', year: '1978', director: 'Lau Kar-leung', plot: 'A man studies kung fu at the Shaolin Temple to fight back against the oppressive Manchu government.', tagline: 'The ultimate in martial arts action!', rating: '4.6/5', posterPath: null },
    { id: '54', title: 'Drunken Master', year: '1978', director: 'Yuen Woo-ping', plot: 'A young and mischievous martial artist is caught between respecting his pacifist father\'s wishes or stopping a group of disrespectful foreigners from ruining his town.', tagline: 'The ultimate in martial arts action!', rating: '4.5/5', posterPath: null },
    { id: '55', title: 'Fist of Fury', year: '1972', director: 'Lo Wei', plot: 'A young man seeks vengence for the death of his master at the hands of a rival dojo during the Japanese occupation of Shanghai.', tagline: 'The ultimate in martial arts action!', rating: '4.7/5', posterPath: null },
    { id: '56', title: 'The Way of the Dragon', year: '1972', director: 'Bruce Lee', plot: 'A man visits his relatives at their restaurant in Italy and has to help them fight against the local gangsters.', tagline: 'The ultimate in martial arts action!', rating: '4.6/5', posterPath: null },
    { id: '57', title: 'Hero', year: '2002', director: 'Zhang Yimou', plot: 'A defense officer, Nameless, was summoned by the King of Qin regarding his success of terminating three warriors.', tagline: 'One man will challenge an empire.', rating: '4.7/5', posterPath: null },
    { id: '58', title: 'House of Flying Daggers', year: '2004', director: 'Zhang Yimou', plot: 'During the reign of the Tang dynasty in China, a secret organization called "The House of Flying Daggers" rises and opposes the government.', tagline: 'Love is a battlefield.', rating: '4.5/5', posterPath: null },
    { id: '59', title: 'Ip Man', year: '2008', director: 'Wilson Yip', plot: 'During the Japanese invasion of 1937, when a wealthy martial artist is forced to leave his home and work to support his family, he reluctantly agrees to train others in the art of Wing Chun for self-defense.', tagline: 'The legend of Wing Chun.', rating: '4.8/5', posterPath: null },
    { id: '60', title: 'Kill Bill: Vol. 1', year: '2003', director: 'Quentin Tarantino', plot: 'After awakening from a four-year coma, a former assassin wreaks vengeance on the team of assassins who betrayed her.', tagline: 'Revenge is a dish best served cold.', rating: '4.6/5', posterPath: null },
  ],
};

// Helper function to get a random movie by genre
export const getMovieByGenre = (genre) => {
  const movies = MOVIES_BY_GENRE[genre] || [];
  if (movies.length === 0) return null;
  
  // Randomly pick a movie from the list
  const randomIndex = Math.floor(Math.random() * movies.length);
  return movies[randomIndex];
};

// Helper function to get all movies for a genre
export const getAllMoviesByGenre = (genre) => {
  return MOVIES_BY_GENRE[genre] || [];
};

